name: Docker Image CI
env:
  CRW_BUILD_USER : "urvashisharma@eaton.com"
  CRW_BUILD_TOKEN : "Welcome@123"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  APP_NAME: ""
  IMAGE_TAGS: ""
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:

    runs-on: ubuntu-latest
    
    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
  
      - name: Determine app name
        if: env.APP_NAME == ''
        run: |
          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
          
      - name: Determine image tags
        if: env.IMAGE_TAGS == ''
        run: |
          echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
          
      - name: Login to RHEC
        uses: docker/login-action@v1
        with:
          username: ${{ env.CRW_BUILD_USER }}
          password: ${{ env.CRW_BUILD_TOKEN }}
          registry: registry.redhat.io
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag target-account-planner:$(date +%s)

      - name: Build from Dockerfile
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          dockerfiles: |
            ./Dockerfile
            
      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_REGISTRY_USER }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
