name: Docker Image CI
env:
  APP_NAME: ""
  IMAGE_TAGS: ""

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Build image  

    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Determine app name
      if: env.APP_NAME == ''
      run: |
        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
        
    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: |
        echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
        
 #    - uses: actions/checkout@v3
    # - name: Build the Docker image
     #  run: docker build . --file Dockerfile --tag target-account-planner:$(date +%s)
 
    - name: Build from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: |
            ./Dockerfile
